// German writes adjectives, verbs and adverbs lowercase. A legacy import batch
// entered ~90 of them capitalised ("Rot", "Wütend", "Packen") under its own
// sector names ("Colors" vs "Colours") — and two thirds of those duplicate a
// correct lowercase card the learner already studies. A capitalised headword is
// not cosmetic here: the card face is where the learner reads the spelling.
//
// This pass is deterministic, not editorial:
//   · capitalised card whose lowercase lemma already exists → delete it
//   · otherwise → lowercase the term and rebuild the id
// Multi-word headwords are left alone: "Rad fahren" and "Bezug nehmen auf" open
// with a noun and are correctly capitalised.
//
// The id map it writes feeds src/data/idmap.ts so a learner's FSRS schedule
// follows the rename instead of silently resetting.
//
//   node scripts/corpus/casefix.ts [--write]
import { join } from 'node:path';
import { PATHS } from './config.ts';
import { readJSON, writeJSON, writeText } from './lib.ts';
import { rebuildSectors } from './sectors.ts';
import type { Word } from '../../src/types.ts';

const write = process.argv.includes('--write');
const CASED_POS = new Set(['adjective', 'verb', 'adverb']);

const vocab = readJSON<Word[]>(PATHS.vocab);
const sectors = readJSON<Parameters<typeof rebuildSectors>[1]>(PATHS.sectors);

// Lowercase lemma → the canonical card that already carries it.
const canonical = new Map<string, Word>();
for (const w of vocab) if (w.term === w.term.toLowerCase()) canonical.set(w.term, w);

const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
const dropped: { from: string; to: string }[] = [];
const renamed: { from: string; to: string }[] = [];
const demoted: { id: string; from: string; to: string }[] = [];
const kept: Word[] = [];

// A duplicate pair can disagree about level ("Nah" at A1, "nah" at A2). The
// earlier claim wins: these are core early words, and a learner should not lose
// one from A1 because a capitalised twin got deleted.
const levelOf = new Map<string, string>();
for (const w of vocab) {
  if (!CASED_POS.has(w.pos) || w.term.includes(' ') || !/^[A-ZÄÖÜ]/.test(w.term)) continue;
  const survivor = canonical.get(w.term.toLowerCase());
  if (survivor && LEVELS.indexOf(w.level) < LEVELS.indexOf(survivor.level)) levelOf.set(survivor.id, w.level);
}

for (const w of vocab) {
  const miscased = CASED_POS.has(w.pos) && !w.term.includes(' ') && /^[A-ZÄÖÜ]/.test(w.term);
  if (miscased) {
    const lower = w.term.toLowerCase();
    const survivor = canonical.get(lower);
    if (survivor) {
      const level = levelOf.get(survivor.id) ?? survivor.level;
      dropped.push({ from: w.id, to: `voc:${level}:${lower}` });
      continue;
    }
    const id = `voc:${w.level}:${lower}`;
    renamed.push({ from: w.id, to: id });
    kept.push({ ...w, term: lower, id });
    continue;
  }
  const level = levelOf.get(w.id);
  if (level) {
    const id = `voc:${level}:${w.term}`;
    demoted.push({ id, from: w.level, to: level });
    renamed.push({ from: w.id, to: id });
    kept.push({ ...w, level: level as Word['level'], id });
    continue;
  }
  kept.push(w);
}

// Sector counts are stored, so they have to follow the deletions. Only the
// counts move: the file keeps its existing order so the diff stays readable.
const fresh = new Map(rebuildSectors(kept, sectors).map((s) => [s.name, s]));
const newSectors = sectors.map((s) => fresh.get(s.name) ?? { ...s, count: 0, levels: [] })
  .filter((s) => s.count > 0);

console.log(`dropped ${dropped.length} duplicates · renamed ${renamed.length} · corpus ${vocab.length} → ${kept.length}`);
for (const d of demoted) console.log(`  level  ${d.id}: ${d.from} → ${d.to} (kept the earlier claim)`);
for (const d of dropped) console.log(`  drop   ${d.from}  →  ${d.to}`);
for (const r of renamed) console.log(`  rename ${r.from}  →  ${r.to}`);

const map = Object.fromEntries([...dropped, ...renamed].map(({ from, to }) => [from, to]));
const migration = `// Generated by scripts/corpus/casefix.ts — do not edit by hand.
// Old card id → the id that replaced it, so a stored FSRS schedule survives a
// corpus correction instead of quietly resetting to new.
export const ID_MAP: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;

if (write) {
  writeJSON(PATHS.vocab, kept);
  writeJSON(PATHS.sectors, newSectors);
  writeText(join(PATHS.repoRoot, 'src', 'data', 'idmap.ts'), migration);
  console.log('Wrote public/data/{vocab,sectors}.json and src/data/idmap.ts');
} else {
  console.log('Dry run — re-run with --write.');
}
