// Emit `public/data/freq.json` — the card-id → frequency-rank map the session
// builder uses to put the commonest words in a CEFR band first.
//
// Why a second file rather than reading provenance.json, which already holds the
// ranks. Provenance is 609 KB and is fetched lazily, on the rare occasion a learner
// opens a card's detail; that trade was argued in `src/lib/provenance.ts` and it is
// still right *for provenance*. But a rank used for scheduling is needed on every
// session build, synchronously, at boot — a different job with a different budget.
// This file is the projection of provenance that scheduling actually needs, and it
// is roughly a fifteenth of the size.
//
// Why not fold the rank into vocab.json: it would be regenerated by the full
// pipeline, which is human-gated (see CLAUDE.md), so a rank refresh would drag a
// lexicon rebuild behind it. This script is deterministic, needs no network, and
// touches nothing but its own output.
//
// Run: npm run corpus:freq
import { readFileSync, writeFileSync } from 'node:fs';

const PROVENANCE = 'public/data/provenance.json';
const VOCAB = 'public/data/vocab.json';
const OUT = 'public/data/freq.json';

interface ProvRow { id: string; freqRank: number | null }
interface VocabRow { id: string; level: string }

const prov: ProvRow[] = JSON.parse(readFileSync(PROVENANCE, 'utf8'));
const vocab: VocabRow[] = JSON.parse(readFileSync(VOCAB, 'utf8'));
const live = new Set(vocab.map((w) => w.id));

const out: Record<string, number> = {};
let dangling = 0;
for (const row of prov) {
  if (row.freqRank == null) continue;
  // A rank for a card the corpus no longer ships is dead weight in a file the app
  // loads at boot. The id-map merges (see src/data/idmap.ts) retire ids routinely.
  if (!live.has(row.id)) { dangling++; continue; }
  out[row.id] = row.freqRank;
}

// Sorted by id so the file is diff-stable: without this a provenance reorder would
// rewrite every line and make a one-word change unreviewable.
const sorted: Record<string, number> = {};
for (const id of Object.keys(out).sort()) sorted[id] = out[id];

writeFileSync(OUT, JSON.stringify(sorted) + '\n');

const covered = Object.keys(sorted).length;
const pct = ((covered / vocab.length) * 100).toFixed(1);
const bytes = readFileSync(OUT).length;
console.log(`freq.json: ${covered} of ${vocab.length} cards (${pct}%), ${(bytes / 1024).toFixed(0)} KB`);
if (dangling) console.log(`  skipped ${dangling} rank(s) for ids the corpus no longer ships`);
if (covered < vocab.length) {
  console.log(`  ${vocab.length - covered} cards have no rank — they predate the provenance log.`);
  console.log('  Unranked cards sort after ranked ones; see weakestSectors in src/store.ts.');
}
