// Parsers for the four sources Lexi's reader can fetch from a browser.
//
// Pure string → data, no DOM, so the node test suite can run them and a worker
// could. The markup is machine-generated by each publisher's CMS and regular
// enough for targeted patterns; each parser reads only the fields it needs and
// returns nothing rather than guessing when the shape is not what it expects.
//
// Fixtures in `parse.test.ts` are hand-written in each source's shape. No
// publisher text is committed: Tagesschau's terms allow private use of the API
// and forbid republishing, and a test fixture in a public repo is publishing.
import type { Article, Para, SourceId } from './types.ts';

// ---- text utilities -----------------------------------------------------------

const NAMED: Record<string, string> = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ', shy: '',
  auml: 'ä', ouml: 'ö', uuml: 'ü', Auml: 'Ä', Ouml: 'Ö', Uuml: 'Ü', szlig: 'ß',
  laquo: '«', raquo: '»', bdquo: '„', ldquo: '“', rdquo: '”', lsquo: '‘', rsquo: '’', sbquo: '‚',
  ndash: '–', mdash: '—', hellip: '…', euro: '€', eacute: 'é', egrave: 'è', agrave: 'à',
};

export function decodeEntities(s: string): string {
  return s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, e: string) => {
    if (e[0] === '#') {
      const code = e[1] === 'x' || e[1] === 'X' ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : m;
    }
    return NAMED[e] ?? m;
  });
}

/** Tags out, entities decoded, whitespace collapsed. */
export function textOf(html: string): string {
  return decodeEntities(html.replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]+>/g, ''))
    .replace(/­/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const unCdata = (s: string) => s.replace(/^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/, '$1');

function tag(block: string, name: string): string | null {
  const m = block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`, 'i'));
  return m ? unCdata(m[1]) : null;
}
function attr(block: string, name: string, attribute: string): string | null {
  const m = block.match(new RegExp(`<${name}\\s[^>]*${attribute}="([^"]*)"`, 'i'));
  return m ? decodeEntities(m[1]) : null;
}

/** A stable short hash, for ids built from URLs. */
export function hashId(s: string): string {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36);
}

// ---- tagesschau (api2u JSON) ----------------------------------------------------

interface TsItem {
  sophoraId?: string; externalId?: string; title?: string; topline?: string; firstSentence?: string;
  date?: string; details?: string; shareURL?: string; detailsweb?: string; type?: string;
  tags?: { tag: string }[]; ressort?: string; breakingNews?: boolean;
}

/** News list → articles. Only `story` items: videos have no text to read. */
export function parseTagesschauList(json: unknown): Article[] {
  const news = (json as { news?: TsItem[] } | null)?.news;
  if (!Array.isArray(news)) return [];
  const out: Article[] = [];
  for (const n of news) {
    if (n.type !== 'story' || !n.details || !n.title) continue;
    const url = n.shareURL || n.detailsweb || '';
    out.push({
      id: `tagesschau:${n.sophoraId || n.externalId || hashId(n.details)}`,
      source: 'tagesschau',
      url,
      title: n.title.trim(),
      topline: n.topline?.trim() || null,
      teaser: n.firstSentence?.trim() || '',
      published: Date.parse(n.date ?? '') || 0,
      tags: (n.tags ?? []).map((t) => t.tag).filter(Boolean),
      detail: n.details,
      audio: null,
      fullText: true,
    });
  }
  return out;
}

/** Article JSON → paragraphs. Keeps running text and in-article headings; drops
 *  boxes, related links, embeds and quotes-as-widgets. */
export function parseTagesschauDetail(json: unknown): Para[] {
  const content = (json as { content?: { type?: string; value?: string }[] } | null)?.content;
  if (!Array.isArray(content)) return [];
  const out: Para[] = [];
  for (const b of content) {
    if (!b.value) continue;
    if (b.type === 'text') {
      const t = textOf(b.value);
      // Credit and programme lines — "tagesschau24 | Nachrichten | 24.09.2026 | 10:00 Uhr",
      // "Mit Informationen von …" — are metadata, not prose.
      if (!t || /^(Mit Informationen von|Dieses Thema im Programm|Über dieses Thema berichtete)/.test(t)) continue;
      if ((t.match(/\s\|\s/g) ?? []).length >= 2) continue;
      out.push({ kind: 'p', text: t });
    } else if (b.type === 'headline') {
      const t = textOf(b.value);
      if (t) out.push({ kind: 'h', text: t });
    }
  }
  return out;
}

// ---- RSS 2.0 and Atom -------------------------------------------------------------

/** One parser for both syndication formats. `source` decides the id prefix and
 *  whether a full text can be fetched later. */
export function parseFeed(xml: string, source: SourceId): Article[] {
  const out: Article[] = [];
  const items = xml.match(/<item[\s>][\s\S]*?<\/item>/gi) ?? [];
  for (const it of items) {
    const title = textOf(tag(it, 'title') ?? '');
    const link = textOf(tag(it, 'link') ?? '') || attr(it, 'guid', 'isPermaLink') || '';
    if (!title || !link) continue;
    const desc = tag(it, 'description') ?? '';
    out.push({
      id: `${source}:${hashId(link.replace(/[?#].*$/, ''))}`,
      source,
      url: link,
      ...splitTitle(title, source),
      teaser: teaserOf(desc),
      published: Date.parse(tag(it, 'pubDate') ?? tag(it, 'dc:date') ?? '') || 0,
      tags: (it.match(/<category[^>]*>([\s\S]*?)<\/category>/gi) ?? []).map((c) => textOf(unCdata(c.replace(/<\/?category[^>]*>/gi, '')))).filter(Boolean),
      detail: source === 'heise' ? null : link,
      audio: attr(it, 'enclosure', 'url'),
      fullText: source !== 'heise',
    });
  }
  const entries = xml.match(/<entry[\s>][\s\S]*?<\/entry>/gi) ?? [];
  for (const e of entries) {
    const title = textOf(tag(e, 'title') ?? '');
    const link = attr(e, 'link', 'href') ?? '';
    if (!title || !link) continue;
    out.push({
      id: `${source}:${hashId(link.replace(/[?#].*$/, ''))}`,
      source,
      url: link,
      ...splitTitle(title, source),
      teaser: teaserOf(tag(e, 'summary') ?? tag(e, 'content') ?? ''),
      published: Date.parse(tag(e, 'published') ?? tag(e, 'updated') ?? '') || 0,
      tags: [],
      detail: null,
      audio: null,
      fullText: false,
    });
  }
  return out;
}

/** SRF titles are "Topline – Headline"; DW's slow news is "date – series name";
 *  everyone else's are just the headline. */
function splitTitle(title: string, source: SourceId): { title: string; topline: string | null } {
  if (source === 'dw') {
    const m = title.match(/^(\d{2}\.\d{2}\.\d{4})\s+–\s+(.+)$/);
    if (m) return { topline: m[1], title: 'Langsam gesprochene Nachrichten' };
  }
  if (source === 'srf') {
    const m = title.match(/^(.{3,80}?)\s+–\s+(.+)$/);
    if (m) return { topline: m[1].trim(), title: m[2].trim() };
  }
  return { title, topline: null };
}

/** A description is often HTML with an image and a "read more"; keep the prose. */
function teaserOf(desc: string): string {
  const t = textOf(decodeEntities(desc));
  return t.length > 400 ? t.slice(0, 397).trimEnd() + '…' : t;
}

// ---- SRF article page ---------------------------------------------------------------

/** The article body of an srf.ch page: paragraphs and in-article headings, in
 *  order, from inside the `articleBody` section only — the page around it carries
 *  navigation, promos and a most-read list. */
export function parseSrfArticle(html: string): Para[] {
  const start = html.search(/itemprop="articleBody"/);
  if (start < 0) return [];
  const body = html.slice(start, html.indexOf('</section>', start) > 0 ? html.indexOf('</section>', start) : undefined);
  const out: Para[] = [];
  const re = /<(p|h2|h3)\b[^>]*class="([^"]*)"[^>]*>([\s\S]*?)<\/\1>/g;
  for (let m = re.exec(body); m; m = re.exec(body)) {
    const [, el, cls, inner] = m;
    const t = textOf(inner);
    if (!t) continue;
    if (el === 'p' && /article-paragraph/.test(cls)) {
      // Broadcast promos ("… gibt's live bei SRF:") are not the story.
      if (/live bei SRF:?$|bei SRF (zwei|info|1):?$/.test(t)) continue;
      out.push({ kind: 'p', text: t });
    } else if (el !== 'p' && /article-heading|article-subheading/.test(cls)) {
      out.push({ kind: 'h', text: t });
    }
  }
  return trimHeadings(out);
}

/** A heading with nothing after it introduced a table or a widget that was
 *  dropped ("Resultate"); it is not part of the story. */
function trimHeadings(paras: Para[]): Para[] {
  while (paras.length && paras[paras.length - 1].kind === 'h') paras.pop();
  return paras;
}

// ---- DW Learn German page -------------------------------------------------------------

/** learngerman.dw.com is client-rendered; the article's HTML travels inside the
 *  page's Apollo state as a JSON string. Pull that string, decode it, split it. */
export function parseDwArticle(html: string): Para[] {
  const m = html.match(/"Article:\d+":\{"__typename":"Article","id":\d+,"text":"((?:[^"\\]|\\.)*)"/);
  if (!m) return [];
  let inner: string;
  try { inner = JSON.parse(`"${m[1]}"`) as string; } catch { return []; }
  const out: Para[] = [];
  const re = /<(p|h2|h3)\b[^>]*>([\s\S]*?)<\/\1>/g;
  for (let x = re.exec(inner); x; x = re.exec(inner)) {
    const t = textOf(x[2]);
    if (t) out.push({ kind: x[1] === 'p' ? 'p' : 'h', text: t });
  }
  return out;
}
