// AUTO-PORTED from the verse-cards prototype (single source of truth for seed content).
// Themed demo decks + the A1–C2 frequency word lists. Regenerate, do not hand-edit.
export type WordPair = [string, string];
export interface ThemedCard { front: string; back: string; example?: string; pos?: string; level?: string; }
export interface ThemedDeck { id: string; name: string; emoji?: string; desc: string; lang: string; cards: ThemedCard[]; }

export const THEMED_DECKS: ThemedDeck[] = [
  { id: 'finanz', name: 'Finanzmärkte', emoji: '📈', desc: 'Markets, investing & economics', lang: 'de', cards: [
    { front: 'die Aktie', back: 'share / stock', example: 'Er legt sein Geld vor allem in Aktien an.', pos: 'Nomen', level: 'B2' },
    { front: 'die Anleihe', back: 'bond', example: 'Staatsanleihen gelten als relativ sichere Geldanlage.', pos: 'Nomen', level: 'B2' },
    { front: 'die Rendite', back: 'yield / return', example: 'Die Rendite dieser Anlage liegt bei vier Prozent.', pos: 'Nomen', level: 'B2' },
    { front: 'der Leitzins', back: 'key interest rate', example: 'Die Zentralbank hat den Leitzins erneut angehoben.', pos: 'Nomen', level: 'C1' },
    { front: 'die Inflation', back: 'inflation', example: 'Die hohe Inflation schmälert die Kaufkraft.', pos: 'Nomen', level: 'B2' },
    { front: 'die Dividende', back: 'dividend', example: 'Das Unternehmen schüttet eine hohe Dividende aus.', pos: 'Nomen', level: 'B2' },
    { front: 'das Wertpapier', back: 'security', example: 'Wertpapiere werden an der Börse gehandelt.', pos: 'Nomen', level: 'B2' },
    { front: 'die Liquidität', back: 'liquidity', example: 'Dem Unternehmen fehlt es an Liquidität.', pos: 'Nomen', level: 'C1' },
    { front: 'die Zinswende', back: 'interest-rate turnaround', example: 'Mit der Zinswende endete die Phase des billigen Geldes.', pos: 'Nomen', level: 'C1' },
    { front: 'der Anleger', back: 'investor', example: 'Vorsichtige Anleger streuen ihr Risiko.', pos: 'Nomen', level: 'B2' },
    { front: 'die Börse', back: 'stock exchange', example: 'An der Börse ging es heute bergab.', pos: 'Nomen', level: 'B1' },
    { front: 'der Kurs', back: 'price / quote (of a security)', example: 'Der Kurs der Aktie brach um zehn Prozent ein.', pos: 'Nomen', level: 'B2' },
    { front: 'die Volatilität', back: 'volatility', example: 'Die Volatilität an den Märkten hat zugenommen.', pos: 'Nomen', level: 'C1' },
    { front: 'der Vermögenswert', back: 'asset', example: 'Immobilien sind ein beliebter Vermögenswert.', pos: 'Nomen', level: 'C1' },
    { front: 'die Geldanlage', back: 'investment', example: 'Diese Geldanlage wirft kaum noch Zinsen ab.', pos: 'Nomen', level: 'B2' },
    { front: 'der Abschwung', back: 'downturn', example: 'Die Wirtschaft steuert auf einen Abschwung zu.', pos: 'Nomen', level: 'C1' },
    { front: 'die Rezession', back: 'recession', example: 'In der Rezession steigt die Arbeitslosigkeit.', pos: 'Nomen', level: 'B2' },
    { front: 'das Risiko streuen', back: 'to diversify (spread) risk', example: 'Wer das Risiko streut, verliert seltener alles.', pos: 'Wendung', level: 'C1' },
    { front: 'Bullen- vs. Bärenmarkt', back: 'bull vs. bear market', example: 'Im Bärenmarkt überwiegt der Pessimismus.', pos: 'Konzept', level: 'C1' },
    { front: 'etwas auf Pump kaufen', back: 'to buy on credit', example: 'Viele finanzieren ihren Konsum auf Pump.', pos: 'Redewendung', level: 'C1' }
  ]},
  { id: 'immo', name: 'Immobilien & Umzug', emoji: '🏠', desc: 'Housing, renting & moving to Köln', lang: 'de', cards: [
    { front: 'der Mietvertrag', back: 'lease / rental contract', example: 'Der Mietvertrag läuft über zwei Jahre.', pos: 'Nomen', level: 'B1' },
    { front: 'die Kaution', back: 'security deposit', example: 'Die Kaution beträgt drei Kaltmieten.', pos: 'Nomen', level: 'B2' },
    { front: 'die Nebenkosten', back: 'utility / incidental costs', example: 'Die Nebenkosten sind in der Miete nicht enthalten.', pos: 'Nomen', level: 'B2' },
    { front: 'der Makler', back: 'real-estate agent', example: 'Der Makler verlangt eine hohe Provision.', pos: 'Nomen', level: 'B2' },
    { front: 'die Wohnungsbesichtigung', back: 'flat viewing', example: 'Zur Wohnungsbesichtigung kamen zwanzig Bewerber.', pos: 'Nomen', level: 'B2' },
    { front: 'die Anmeldung', back: 'registration of residence', example: 'Nach dem Umzug ist die Anmeldung beim Bürgeramt Pflicht.', pos: 'Nomen', level: 'B1' },
    { front: 'die Ummeldung', back: 're-registration (new address)', example: 'Für die Ummeldung braucht man eine Wohnungsgeberbestätigung.', pos: 'Nomen', level: 'C1' },
    { front: 'der Vermieter', back: 'landlord', example: 'Der Vermieter hat die Kaution einbehalten.', pos: 'Nomen', level: 'B1' },
    { front: 'die Hausverwaltung', back: 'property management', example: 'Bei Schäden wendet man sich an die Hausverwaltung.', pos: 'Nomen', level: 'B2' },
    { front: 'die Kaltmiete', back: 'base ("cold") rent', example: 'Die Kaltmiete liegt bei 900 Euro.', pos: 'Nomen', level: 'B2' },
    { front: 'die Warmmiete', back: 'rent including utilities', example: 'Die Warmmiete enthält Heizung und Wasser.', pos: 'Nomen', level: 'B2' },
    { front: 'die Wohnungsgeberbestätigung', back: "landlord's confirmation of residence", example: 'Ohne Wohnungsgeberbestätigung gelingt die Anmeldung nicht.', pos: 'Nomen', level: 'C1' },
    { front: 'das Grundbuch', back: 'land register', example: 'Der Eigentümer ist im Grundbuch eingetragen.', pos: 'Nomen', level: 'C1' },
    { front: 'die Eigentumswohnung', back: 'owner-occupied flat / condo', example: 'Sie haben eine Eigentumswohnung in Köln gekauft.', pos: 'Nomen', level: 'B2' },
    { front: 'der Quadratmeter', back: 'square metre', example: 'Die Wohnung hat achtzig Quadratmeter.', pos: 'Nomen', level: 'B1' },
    { front: 'die Genossenschaft', back: '(housing) cooperative', example: 'Bei einer Genossenschaft ist die Miete oft günstiger.', pos: 'Nomen', level: 'C1' },
    { front: 'der Umzug', back: 'move / relocation', example: 'Der Umzug nach Köln steht kurz bevor.', pos: 'Nomen', level: 'B1' },
    { front: 'die Hausordnung', back: 'house rules', example: 'Laut Hausordnung herrscht ab 22 Uhr Ruhe.', pos: 'Nomen', level: 'B2' },
    { front: 'die Provision', back: 'commission (fee)', example: 'Beim Kauf fällt eine Maklerprovision an.', pos: 'Nomen', level: 'B2' },
    { front: 'eine Kaution hinterlegen', back: 'to put down a deposit', example: 'Vor dem Einzug muss man die Kaution hinterlegen.', pos: 'Wendung', level: 'C1' }
  ]},
  { id: 'ki', name: 'KI & Technik', emoji: '🤖', desc: 'AI, software & technology', lang: 'de', cards: [
    { front: 'die künstliche Intelligenz', back: 'artificial intelligence', example: 'Künstliche Intelligenz verändert die Arbeitswelt.', pos: 'Nomen', level: 'B2' },
    { front: 'das maschinelle Lernen', back: 'machine learning', example: 'Maschinelles Lernen erkennt Muster in großen Datenmengen.', pos: 'Nomen', level: 'C1' },
    { front: 'der Algorithmus', back: 'algorithm', example: 'Der Algorithmus entscheidet, welche Beiträge du siehst.', pos: 'Nomen', level: 'B2' },
    { front: 'das Sprachmodell', back: 'language model', example: 'Große Sprachmodelle erzeugen erstaunlich flüssige Texte.', pos: 'Nomen', level: 'C1' },
    { front: 'der Datensatz', back: 'data set', example: 'Das Modell wurde mit einem riesigen Datensatz trainiert.', pos: 'Nomen', level: 'C1' },
    { front: 'die Rechenleistung', back: 'computing power', example: 'Das Training erfordert enorme Rechenleistung.', pos: 'Nomen', level: 'C1' },
    { front: 'die Schnittstelle', back: 'interface', example: 'Über eine Schnittstelle greifen Programme auf die Daten zu.', pos: 'Nomen', level: 'C1' },
    { front: 'der Datenschutz', back: 'data protection / privacy', example: 'Der Datenschutz ist in Europa streng geregelt.', pos: 'Nomen', level: 'B2' },
    { front: 'das neuronale Netz', back: 'neural network', example: 'Neuronale Netze sind dem menschlichen Gehirn nachempfunden.', pos: 'Nomen', level: 'C1' },
    { front: 'die Automatisierung', back: 'automation', example: 'Die Automatisierung bedroht einfache Tätigkeiten.', pos: 'Nomen', level: 'B2' },
    { front: 'der Fortschritt', back: 'progress', example: 'Der technische Fortschritt lässt sich kaum aufhalten.', pos: 'Nomen', level: 'B2' },
    { front: 'die Verschlüsselung', back: 'encryption', example: 'Dank Verschlüsselung bleiben die Nachrichten geheim.', pos: 'Nomen', level: 'C1' },
    { front: 'der Quellcode', back: 'source code', example: 'Der Quellcode ist frei zugänglich.', pos: 'Nomen', level: 'C1' },
    { front: 'die Benutzeroberfläche', back: 'user interface', example: 'Die Benutzeroberfläche ist übersichtlich gestaltet.', pos: 'Nomen', level: 'B2' },
    { front: 'die Datenmenge', back: 'volume of data', example: 'Solche Datenmengen kann kein Mensch mehr überblicken.', pos: 'Nomen', level: 'B2' },
    { front: 'die Trainingsdaten', back: 'training data', example: 'Die Trainingsdaten bestimmen, was das Modell lernt.', pos: 'Nomen', level: 'C1' },
    { front: 'die Voreingenommenheit', back: 'bias', example: 'Verzerrte Trainingsdaten führen zu Voreingenommenheit.', pos: 'Nomen', level: 'C1' },
    { front: 'quelloffene Software', back: 'open-source software', example: 'Verse soll quelloffene Software sein.', pos: 'Nomen', level: 'C1' },
    { front: 'etwas in Echtzeit verarbeiten', back: 'to process in real time', example: 'Das System verarbeitet die Anfragen in Echtzeit.', pos: 'Wendung', level: 'C1' },
    { front: 'auf dem neuesten Stand sein', back: 'to be up to date', example: 'Die Software ist auf dem neuesten Stand.', pos: 'Redewendung', level: 'B2' }
  ]},
  { id: 'politik', name: 'Politik & Nachhaltigkeit', emoji: '🌍', desc: 'Politics, economy & sustainability', lang: 'de', cards: [
    { front: 'der Bundestag', back: 'federal parliament', example: 'Der Bundestag verabschiedete das Gesetz.', pos: 'Nomen', level: 'B2' },
    { front: 'die Koalition', back: 'coalition', example: 'Die Koalition stritt über den Haushalt.', pos: 'Nomen', level: 'B2' },
    { front: 'der Gesetzentwurf', back: 'bill / draft law', example: 'Der Gesetzentwurf stieß auf Widerstand.', pos: 'Nomen', level: 'C1' },
    { front: 'die Energiewende', back: 'energy transition', example: 'Die Energiewende erfordert massive Investitionen.', pos: 'Nomen', level: 'C1' },
    { front: 'der Klimawandel', back: 'climate change', example: 'Der Klimawandel verschärft die Dürren.', pos: 'Nomen', level: 'B2' },
    { front: 'erneuerbare Energien', back: 'renewable energy', example: 'Erneuerbare Energien decken einen wachsenden Teil des Bedarfs.', pos: 'Nomen', level: 'B2' },
    { front: 'die Emissionen', back: 'emissions', example: 'Die Emissionen müssen drastisch sinken.', pos: 'Nomen', level: 'B2' },
    { front: 'die Nachhaltigkeit', back: 'sustainability', example: 'Nachhaltigkeit ist mehr als ein Schlagwort.', pos: 'Nomen', level: 'B2' },
    { front: 'der Kompromiss', back: 'compromise', example: 'Nach langem Ringen fanden sie einen Kompromiss.', pos: 'Nomen', level: 'B2' },
    { front: 'die Abstimmung', back: 'vote / ballot', example: 'Bei der Abstimmung gab es keine Mehrheit.', pos: 'Nomen', level: 'B2' },
    { front: 'die Mehrheit', back: 'majority', example: 'Die Regierung verfügt über eine knappe Mehrheit.', pos: 'Nomen', level: 'B1' },
    { front: 'die Opposition', back: 'opposition', example: 'Die Opposition kritisierte den Haushalt scharf.', pos: 'Nomen', level: 'B2' },
    { front: 'die Wahlbeteiligung', back: 'voter turnout', example: 'Die Wahlbeteiligung war diesmal besonders hoch.', pos: 'Nomen', level: 'C1' },
    { front: 'der CO₂-Ausstoß', back: 'CO₂ emissions', example: 'Der Verkehr verursacht einen großen Teil des CO₂-Ausstoßes.', pos: 'Nomen', level: 'C1' },
    { front: 'die Subvention', back: 'subsidy', example: 'Subventionen sollen den Umstieg erleichtern.', pos: 'Nomen', level: 'C1' },
    { front: 'der Treibhauseffekt', back: 'greenhouse effect', example: 'Treibhausgase verstärken den Treibhauseffekt.', pos: 'Nomen', level: 'C1' },
    { front: 'die Verkehrswende', back: 'transport transition', example: 'Die Verkehrswende setzt auf Bus, Bahn und Rad.', pos: 'Nomen', level: 'C1' },
    { front: 'der Steuerzahler', back: 'taxpayer', example: 'Die Kosten trägt am Ende der Steuerzahler.', pos: 'Nomen', level: 'B2' },
    { front: 'ein Gesetz verabschieden', back: 'to pass a law', example: 'Das Parlament hat das Gesetz verabschiedet.', pos: 'Wendung', level: 'B2' },
    { front: 'auf Kosten künftiger Generationen', back: 'at the expense of future generations', example: 'Wir leben auf Kosten künftiger Generationen.', pos: 'Redewendung', level: 'C1' }
  ]}
];

export const FREQ: Record<string, WordPair[]> = {
  A1: [
    ['der Mann', 'man'], ['die Frau', 'woman'], ['das Kind', 'child'], ['das Haus', 'house'], ['die Stadt', 'city'],
    ['das Land', 'country'], ['der Tag', 'day'], ['die Nacht', 'night'], ['das Jahr', 'year'], ['die Zeit', 'time'],
    ['das Wasser', 'water'], ['das Essen', 'food'], ['das Brot', 'bread'], ['der Kaffee', 'coffee'], ['die Milch', 'milk'],
    ['der Freund', 'friend'], ['die Familie', 'family'], ['die Mutter', 'mother'], ['der Vater', 'father'], ['die Schule', 'school'],
    ['die Arbeit', 'work'], ['das Auto', 'car'], ['der Zug', 'train'], ['die Straße', 'street'], ['das Zimmer', 'room'],
    ['die Tür', 'door'], ['das Fenster', 'window'], ['der Tisch', 'table'], ['der Stuhl', 'chair'], ['das Buch', 'book'],
    ['der Name', 'name'], ['die Sprache', 'language'], ['das Wort', 'word'], ['die Frage', 'question'], ['die Hand', 'hand'],
    ['der Kopf', 'head'], ['das Auge', 'eye'], ['der Tag', 'day'], ['das Geld', 'money'], ['der Markt', 'market'],
    ['sein', 'to be'], ['haben', 'to have'], ['werden', 'to become'], ['können', 'can / to be able to'], ['müssen', 'must / to have to'],
    ['machen', 'to do / make'], ['gehen', 'to go'], ['kommen', 'to come'], ['sehen', 'to see'], ['wissen', 'to know'],
    ['sagen', 'to say'], ['geben', 'to give'], ['nehmen', 'to take'], ['finden', 'to find'], ['essen', 'to eat'],
    ['trinken', 'to drink'], ['sprechen', 'to speak'], ['wohnen', 'to live (reside)'], ['kaufen', 'to buy'], ['lernen', 'to learn'],
    ['arbeiten', 'to work'], ['spielen', 'to play'], ['lieben', 'to love'], ['fahren', 'to drive / go'], ['schlafen', 'to sleep'],
    ['gut', 'good'], ['schlecht', 'bad'], ['groß', 'big'], ['klein', 'small'], ['neu', 'new'],
    ['alt', 'old'], ['jung', 'young'], ['schön', 'beautiful'], ['warm', 'warm'], ['kalt', 'cold'],
    ['viel', 'much / a lot'], ['wenig', 'little / few'], ['hier', 'here'], ['dort', 'there'], ['heute', 'today'],
    ['morgen', 'tomorrow'], ['gestern', 'yesterday'], ['jetzt', 'now'], ['immer', 'always'], ['nie', 'never'],
    ['ja', 'yes'], ['nein', 'no'], ['nicht', 'not'], ['und', 'and'], ['oder', 'or'],
    ['aber', 'but'], ['weil', 'because'], ['wenn', 'if / when'], ['mit', 'with'], ['ohne', 'without'],
    ['für', 'for'], ['gegen', 'against'], ['über', 'over / about'], ['unter', 'under'], ['nach', 'after / to'],
    ['vor', 'before / in front of'], ['bei', 'at / near'], ['eins', 'one'], ['zwei', 'two'], ['drei', 'three']
  ],
  A2: [
    ['die Reise', 'trip / journey'], ['der Urlaub', 'holiday / vacation'], ['das Wetter', 'weather'], ['die Sonne', 'sun'], ['der Regen', 'rain'],
    ['der Schnee', 'snow'], ['der Wind', 'wind'], ['der Himmel', 'sky'], ['der Berg', 'mountain'], ['das Meer', 'sea'],
    ['der See', 'lake'], ['der Wald', 'forest'], ['das Tier', 'animal'], ['der Hund', 'dog'], ['die Katze', 'cat'],
    ['der Vogel', 'bird'], ['der Baum', 'tree'], ['die Blume', 'flower'], ['die Farbe', 'colour'], ['das Bild', 'picture'],
    ['die Musik', 'music'], ['der Film', 'film / movie'], ['das Spiel', 'game'], ['der Sport', 'sport'], ['die Mannschaft', 'team'],
    ['die Gesundheit', 'health'], ['die Krankheit', 'illness'], ['der Arzt', 'doctor'], ['das Krankenhaus', 'hospital'], ['die Apotheke', 'pharmacy'],
    ['das Geschäft', 'shop / business'], ['der Preis', 'price'], ['das Angebot', 'offer'], ['die Rechnung', 'bill / invoice'], ['der Kunde', 'customer'],
    ['der Beruf', 'profession'], ['die Stelle', 'job / position'], ['der Chef', 'boss'], ['der Kollege', 'colleague'], ['das Büro', 'office'],
    ['die Wohnung', 'flat / apartment'], ['die Miete', 'rent'], ['der Nachbar', 'neighbour'], ['der Schlüssel', 'key'], ['der Aufzug', 'lift / elevator'],
    ['das Frühstück', 'breakfast'], ['das Mittagessen', 'lunch'], ['das Abendessen', 'dinner'], ['der Hunger', 'hunger'], ['der Durst', 'thirst'],
    ['anfangen', 'to begin'], ['aufhören', 'to stop'], ['bezahlen', 'to pay'], ['bestellen', 'to order'], ['brauchen', 'to need'],
    ['bringen', 'to bring'], ['denken', 'to think'], ['erklären', 'to explain'], ['fragen', 'to ask'], ['antworten', 'to answer'],
    ['glauben', 'to believe'], ['helfen', 'to help'], ['hoffen', 'to hope'], ['holen', 'to fetch'], ['leben', 'to live'],
    ['lesen', 'to read'], ['schreiben', 'to write'], ['suchen', 'to search'], ['treffen', 'to meet'], ['vergessen', 'to forget'],
    ['verkaufen', 'to sell'], ['verstehen', 'to understand'], ['versuchen', 'to try'], ['warten', 'to wait'], ['zeigen', 'to show'],
    ['ändern', 'to change'], ['benutzen', 'to use'], ['besuchen', 'to visit'], ['einladen', 'to invite'], ['mitbringen', 'to bring along'],
    ['wichtig', 'important'], ['richtig', 'correct'], ['falsch', 'wrong'], ['möglich', 'possible'], ['nötig', 'necessary'],
    ['einfach', 'simple / easy'], ['schwierig', 'difficult'], ['schnell', 'fast'], ['langsam', 'slow'], ['früh', 'early'],
    ['spät', 'late'], ['fertig', 'finished / ready'], ['frei', 'free'], ['besetzt', 'occupied'], ['gleich', 'same / shortly'],
    ['zusammen', 'together'], ['allein', 'alone'], ['vielleicht', 'maybe'], ['wahrscheinlich', 'probably'], ['endlich', 'finally'],
    ['plötzlich', 'suddenly'], ['ungefähr', 'approximately'], ['mindestens', 'at least'], ['höchstens', 'at most'], ['eigentlich', 'actually']
  ],
  B1: [
    ['die Erfahrung', 'experience'], ['die Erinnerung', 'memory'], ['die Meinung', 'opinion'], ['die Entscheidung', 'decision'], ['die Lösung', 'solution'],
    ['das Problem', 'problem'], ['die Ursache', 'cause'], ['die Folge', 'consequence'], ['der Grund', 'reason'], ['der Zweck', 'purpose'],
    ['das Ziel', 'goal'], ['die Aufgabe', 'task'], ['die Möglichkeit', 'possibility'], ['die Gelegenheit', 'opportunity'], ['der Vorteil', 'advantage'],
    ['der Nachteil', 'disadvantage'], ['der Unterschied', 'difference'], ['die Beziehung', 'relationship'], ['die Gesellschaft', 'society'], ['die Umwelt', 'environment'],
    ['die Bildung', 'education'], ['die Forschung', 'research'], ['die Wirtschaft', 'economy'], ['die Regierung', 'government'], ['das Gesetz', 'law'],
    ['die Verantwortung', 'responsibility'], ['die Erfahrung', 'experience'], ['die Entwicklung', 'development'], ['die Veränderung', 'change'], ['die Bedeutung', 'meaning / importance'],
    ['der Eindruck', 'impression'], ['die Stimmung', 'mood'], ['das Gefühl', 'feeling'], ['der Gedanke', 'thought'], ['die Vorstellung', 'idea / notion'],
    ['der Vorschlag', 'suggestion'], ['die Absicht', 'intention'], ['das Verhalten', 'behaviour'], ['die Gewohnheit', 'habit'], ['die Fähigkeit', 'ability'],
    ['die Pflicht', 'duty'], ['das Recht', 'right'], ['die Freiheit', 'freedom'], ['die Sicherheit', 'security'], ['die Gefahr', 'danger'],
    ['der Erfolg', 'success'], ['der Versuch', 'attempt'], ['die Leistung', 'achievement / performance'], ['die Anstrengung', 'effort'], ['der Fortschritt', 'progress'],
    ['behaupten', 'to claim'], ['beschreiben', 'to describe'], ['beweisen', 'to prove'], ['empfehlen', 'to recommend'], ['entscheiden', 'to decide'],
    ['entwickeln', 'to develop'], ['erlauben', 'to allow'], ['ermöglichen', 'to make possible'], ['erreichen', 'to reach / achieve'], ['erwarten', 'to expect'],
    ['fördern', 'to promote'], ['gehören', 'to belong'], ['gelingen', 'to succeed'], ['sich kümmern', 'to take care'], ['überlegen', 'to consider'],
    ['überzeugen', 'to convince'], ['unterscheiden', 'to distinguish'], ['vergleichen', 'to compare'], ['vermeiden', 'to avoid'], ['vermuten', 'to assume'],
    ['verändern', 'to change'], ['verbessern', 'to improve'], ['verbieten', 'to forbid'], ['verlangen', 'to demand'], ['verlieren', 'to lose'],
    ['vertrauen', 'to trust'], ['verzichten', 'to do without'], ['vorbereiten', 'to prepare'], ['vorschlagen', 'to suggest'], ['zweifeln', 'to doubt'],
    ['deutlich', 'clear'], ['gründlich', 'thorough'], ['nützlich', 'useful'], ['gefährlich', 'dangerous'], ['erfolgreich', 'successful'],
    ['notwendig', 'necessary'], ['zuverlässig', 'reliable'], ['vorsichtig', 'careful'], ['neugierig', 'curious'], ['zufrieden', 'satisfied'],
    ['selbstständig', 'independent'], ['gemeinsam', 'common / joint'], ['öffentlich', 'public'], ['persönlich', 'personal'], ['ähnlich', 'similar'],
    ['besonders', 'especially'], ['außerdem', 'moreover'], ['trotzdem', 'nevertheless'], ['deshalb', 'therefore'], ['obwohl', 'although'],
    ['damit', 'so that'], ['sobald', 'as soon as'], ['während', 'while / during'], ['je nachdem', 'depending'], ['einerseits', 'on the one hand']
  ],
  B2: [
    ['die Voraussetzung', 'prerequisite'], ['die Herausforderung', 'challenge'], ['die Auswirkung', 'effect / impact'], ['die Maßnahme', 'measure'], ['die Strategie', 'strategy'],
    ['die Tendenz', 'tendency'], ['der Zusammenhang', 'connection / context'], ['der Aspekt', 'aspect'], ['der Bereich', 'area / field'], ['die Grundlage', 'basis'],
    ['die Voraussage', 'prediction'], ['die Annahme', 'assumption'], ['die Behauptung', 'claim'], ['die Schlussfolgerung', 'conclusion'], ['der Widerspruch', 'contradiction'],
    ['die Auseinandersetzung', 'dispute / debate'], ['die Einschätzung', 'assessment'], ['die Wahrnehmung', 'perception'], ['die Überzeugung', 'conviction'], ['die Einstellung', 'attitude'],
    ['der Anspruch', 'claim / demand'], ['der Aufwand', 'effort / expense'], ['der Nutzen', 'benefit'], ['die Belastung', 'burden / strain'], ['die Erleichterung', 'relief'],
    ['die Zunahme', 'increase'], ['die Abnahme', 'decrease'], ['der Rückgang', 'decline'], ['der Anstieg', 'rise'], ['das Gleichgewicht', 'balance'],
    ['die Vielfalt', 'diversity'], ['die Mehrheit', 'majority'], ['die Minderheit', 'minority'], ['der Durchschnitt', 'average'], ['die Ausnahme', 'exception'],
    ['die Genehmigung', 'permission / approval'], ['die Verpflichtung', 'obligation'], ['die Vereinbarung', 'agreement'], ['der Vertrag', 'contract'], ['die Bedingung', 'condition'],
    ['die Begründung', 'justification'], ['die Schwierigkeit', 'difficulty'], ['der Mangel', 'lack / shortage'], ['der Überschuss', 'surplus'], ['die Knappheit', 'scarcity'],
    ['anerkennen', 'to acknowledge'], ['ausschließen', 'to exclude'], ['berücksichtigen', 'to take into account'], ['beeinflussen', 'to influence'], ['beitragen', 'to contribute'],
    ['betonen', 'to emphasise'], ['betreffen', 'to concern / affect'], ['beurteilen', 'to judge'], ['bewerten', 'to evaluate'], ['durchsetzen', 'to assert / push through'],
    ['einschränken', 'to restrict'], ['erfassen', 'to grasp / record'], ['ergänzen', 'to complement'], ['gewährleisten', 'to ensure'], ['hervorheben', 'to highlight'],
    ['nachweisen', 'to prove / demonstrate'], ['scheitern', 'to fail'], ['schließen', 'to conclude / close'], ['umsetzen', 'to implement'], ['unterstützen', 'to support'],
    ['veranlassen', 'to prompt / cause'], ['verursachen', 'to cause'], ['voraussetzen', 'to presuppose'], ['widersprechen', 'to contradict'], ['zusammenfassen', 'to summarise'],
    ['angemessen', 'appropriate'], ['ausführlich', 'detailed'], ['eindeutig', 'unambiguous'], ['erheblich', 'considerable'], ['gravierend', 'serious'],
    ['nachhaltig', 'sustainable'], ['umfangreich', 'extensive'], ['unverzichtbar', 'indispensable'], ['wesentlich', 'essential'], ['zahlreich', 'numerous'],
    ['zunehmend', 'increasingly'], ['vorläufig', 'preliminary'], ['endgültig', 'final'], ['gegenseitig', 'mutual'], ['umstritten', 'controversial'],
    ['anspruchsvoll', 'demanding'], ['aufwendig', 'elaborate / costly'], ['durchschnittlich', 'average'], ['einflussreich', 'influential'], ['unverändert', 'unchanged'],
    ['allerdings', 'however'], ['dennoch', 'nevertheless'], ['folglich', 'consequently'], ['hingegen', 'on the other hand'], ['insofern', 'in that respect'],
    ['nämlich', 'namely'], ['ohnehin', 'anyway'], ['vorausgesetzt', 'provided that'], ['zumal', 'especially since'], ['zwar', 'admittedly']
  ],
  C1: [
    ['die Errungenschaft', 'achievement'], ['die Beeinträchtigung', 'impairment'], ['die Diskrepanz', 'discrepancy'], ['die Ambivalenz', 'ambivalence'], ['die Kohärenz', 'coherence'],
    ['die Plausibilität', 'plausibility'], ['die Souveränität', 'sovereignty'], ['die Legitimität', 'legitimacy'], ['die Transparenz', 'transparency'], ['die Nachhaltigkeit', 'sustainability'],
    ['die Wechselwirkung', 'interaction'], ['die Rahmenbedingung', 'framework condition'], ['der Spielraum', 'leeway / scope'], ['die Reichweite', 'reach / scope'], ['der Stellenwert', 'significance'],
    ['die Tragweite', 'significance / scope'], ['das Ausmaß', 'extent'], ['die Vorgehensweise', 'approach'], ['die Herangehensweise', 'approach'], ['der Sachverhalt', 'state of affairs'],
    ['die Grauzone', 'grey area'], ['der Kompromiss', 'compromise'], ['die Gratwanderung', 'balancing act'], ['der Stellenwert', 'standing / importance'], ['die Verflechtung', 'entanglement'],
    ['die Voreingenommenheit', 'bias'], ['die Befangenheit', 'partiality'], ['die Zwangsläufigkeit', 'inevitability'], ['die Beliebigkeit', 'arbitrariness'], ['der Konsens', 'consensus'],
    ['die Skepsis', 'scepticism'], ['die Zuversicht', 'confidence'], ['die Gelassenheit', 'composure'], ['die Hartnäckigkeit', 'persistence'], ['die Beharrlichkeit', 'tenacity'],
    ['abwägen', 'to weigh up'], ['relativieren', 'to put into perspective'], ['untermauern', 'to substantiate'], ['hinterfragen', 'to question'], ['einräumen', 'to concede'],
    ['nachvollziehen', 'to comprehend'], ['verdeutlichen', 'to clarify'], ['veranschaulichen', 'to illustrate'], ['konkretisieren', 'to make concrete'], ['verallgemeinern', 'to generalise'],
    ['eindämmen', 'to contain / curb'], ['ankurbeln', 'to boost'], ['bewältigen', 'to cope with'], ['entgegenwirken', 'to counteract'], ['herbeiführen', 'to bring about'],
    ['in Kauf nehmen', 'to accept / put up with'], ['in Frage stellen', 'to call into question'], ['Rechnung tragen', 'to take account of'], ['Stellung beziehen', 'to take a stance'], ['Maßstäbe setzen', 'to set standards'],
    ['sich abzeichnen', 'to emerge / loom'], ['sich niederschlagen', 'to be reflected'], ['sich bewähren', 'to prove itself'], ['zugrunde liegen', 'to underlie'], ['ins Auge fassen', 'to envisage'],
    ['ausschlaggebend', 'decisive'], ['maßgeblich', 'authoritative / decisive'], ['gravierend', 'grave'], ['weitreichend', 'far-reaching'], ['tiefgreifend', 'profound'],
    ['unabdingbar', 'indispensable'], ['unumgänglich', 'unavoidable'], ['fragwürdig', 'questionable'], ['vielschichtig', 'multifaceted'], ['differenziert', 'nuanced'],
    ['nachvollziehbar', 'comprehensible'], ['nachweislich', 'demonstrably'], ['augenscheinlich', 'apparently'], ['vermeintlich', 'supposed'], ['ausgeprägt', 'pronounced'],
    ['gängig', 'common / prevailing'], ['stichhaltig', 'valid / sound'], ['triftig', 'cogent'], ['schlüssig', 'conclusive'], ['lückenhaft', 'incomplete'],
    ['bezeichnend', 'characteristic'], ['richtungsweisend', 'trailblazing'], ['folgenschwer', 'momentous'], ['unverhältnismäßig', 'disproportionate'], ['unstrittig', 'undisputed'],
    ['gleichermaßen', 'equally'], ['zusehends', 'visibly / increasingly'], ['unweigerlich', 'inevitably'], ['mitunter', 'occasionally'], ['weitestgehend', 'largely'],
    ['letztlich', 'ultimately'], ['nachgerade', 'downright'], ['gemeinhin', 'commonly'], ['vorrangig', 'primarily'], ['hinlänglich', 'sufficiently'],
    ['ungeachtet', 'regardless of'], ['anhand', 'on the basis of'], ['zugunsten', 'in favour of'], ['hinsichtlich', 'regarding'], ['angesichts', 'in view of']
  ],
  C2: [
    ['die Quintessenz', 'quintessence'], ['die Nuance', 'nuance'], ['die Konnotation', 'connotation'], ['die Implikation', 'implication'], ['die Prämisse', 'premise'],
    ['die Dichotomie', 'dichotomy'], ['das Paradigma', 'paradigm'], ['die Antinomie', 'antinomy'], ['die Kausalität', 'causality'], ['die Kontingenz', 'contingency'],
    ['die Diskursanalyse', 'discourse analysis'], ['die Hermeneutik', 'hermeneutics'], ['die Dialektik', 'dialectics'], ['die Empirie', 'empiricism'], ['die Heuristik', 'heuristics'],
    ['der Topos', 'topos / commonplace'], ['das Narrativ', 'narrative'], ['die Resilienz', 'resilience'], ['die Disruption', 'disruption'], ['die Polarisierung', 'polarisation'],
    ['die Marginalisierung', 'marginalisation'], ['die Stigmatisierung', 'stigmatisation'], ['die Instrumentalisierung', 'instrumentalisation'], ['die Pauschalisierung', 'generalisation'], ['die Relativierung', 'relativisation'],
    ['der Gemeinplatz', 'platitude'], ['die Chiffre', 'cipher / code'], ['die Allegorie', 'allegory'], ['der Euphemismus', 'euphemism'], ['die Hyperbel', 'hyperbole'],
    ['die Ambiguität', 'ambiguity'], ['die Subtilität', 'subtlety'], ['die Vehemenz', 'vehemence'], ['die Akribie', 'meticulousness'], ['die Stringenz', 'stringency / rigour'],
    ['die Kontextualisierung', 'contextualisation'], ['die Differenzierung', 'differentiation'], ['die Verdichtung', 'condensation'], ['die Engführung', 'narrowing'], ['die Zuspitzung', 'escalation / sharpening'],
    ['konstatieren', 'to ascertain'], ['suggerieren', 'to suggest / insinuate'], ['konnotieren', 'to connote'], ['subsumieren', 'to subsume'], ['antizipieren', 'to anticipate'],
    ['kontextualisieren', 'to contextualise'], ['konterkarieren', 'to thwart'], ['kaschieren', 'to conceal'], ['relativieren', 'to qualify'], ['negieren', 'to negate'],
    ['oszillieren', 'to oscillate'], ['transzendieren', 'to transcend'], ['perpetuieren', 'to perpetuate'], ['kulminieren', 'to culminate'], ['eskalieren', 'to escalate'],
    ['sich verselbstständigen', 'to take on a life of its own'], ['ins Wanken geraten', 'to start to falter'], ['zutage treten', 'to come to light'], ['Einzug halten', 'to take hold'], ['Überhand nehmen', 'to get out of hand'],
    ['idiosynkratisch', 'idiosyncratic'], ['ubiquitär', 'ubiquitous'], ['immanent', 'inherent'], ['inhärent', 'inherent'], ['ambivalent', 'ambivalent'],
    ['dezidiert', 'decided / emphatic'], ['eklatant', 'blatant'], ['frappierend', 'striking'], ['gravitätisch', 'solemn / weighty'], ['lapidar', 'terse'],
    ['nuanciert', 'nuanced'], ['prägnant', 'concise / incisive'], ['rekurrent', 'recurrent'], ['signifikant', 'significant'], ['stringent', 'rigorous'],
    ['subversiv', 'subversive'], ['suggestiv', 'suggestive'], ['tendenziös', 'tendentious'], ['konziliant', 'conciliatory'], ['kohärent', 'coherent'],
    ['diametral', 'diametrical'], ['exemplarisch', 'exemplary'], ['kategorisch', 'categorical'], ['paradox', 'paradoxical'], ['profund', 'profound'],
    ['rudimentär', 'rudimentary'], ['marginal', 'marginal'], ['obsolet', 'obsolete'], ['redundant', 'redundant'], ['kontraproduktiv', 'counterproductive'],
    ['mithin', 'consequently'], ['gleichwohl', 'nonetheless'], ['indes', 'however'], ['vorderhand', 'for the time being'], ['zusehends', 'noticeably'],
    ['unbeschadet', 'notwithstanding'], ['vermittels', 'by means of'], ['kraft', 'by virtue of'], ['behufs', 'for the purpose of'], ['zwecks', 'for the purpose of']
  ]
};
