// GENERATED — German term → representative emoji for card meaning-images.
// Built by an AI mapping workflow over the catalog (explore decks + frequency
// lists + themed decks). Only terms with a clear visual match are present;
// everything else falls back to the star glyph. Regenerate, do not hand-edit.
// Coverage: 247 terms (chunks 0-8 of 26; resume run wf_f36ebb0f-1c4 for the rest).
export const EMOJI: Record<string, string> = {
  "die Aktie": "📈",
  "die Börse": "🏛️",
  "der Abschwung": "📉",
  "die Rezession": "📉",
  "etwas auf Pump kaufen": "💳",
  "der Mietvertrag": "📝",
  "der Quadratmeter": "📐",
  "der Umzug": "📦",
  "die künstliche Intelligenz": "🤖",
  "die Schnittstelle": "🔌",
  "der Datenschutz": "🔒",
  "die Verschlüsselung": "🔐",
  "der Quellcode": "💻",
  "der Bundestag": "🏛️",
  "die Koalition": "🤝",
  "der Gesetzentwurf": "📜",
  "erneuerbare Energien": "🌬️",
  "die Emissionen": "🏭",
  "die Nachhaltigkeit": "♻️",
  "die Abstimmung": "🗳️",
  "der CO₂-Ausstoß": "🏭",
  "der Mann": "👨",
  "die Frau": "👩",
  "das Kind": "🧒",
  "das Haus": "🏠",
  "die Stadt": "🏙️",
  "der Tag": "☀️",
  "die Nacht": "🌙",
  "das Jahr": "📅",
  "die Zeit": "⏰",
  "das Wasser": "💧",
  "das Essen": "🍽️",
  "das Brot": "🍞",
  "der Kaffee": "☕",
  "die Milch": "🥛",
  "der Freund": "🤝",
  "die Familie": "👨‍👩‍👧‍👦",
  "die Mutter": "🤱",
  "der Vater": "👨‍🍼",
  "die Schule": "🏫",
  "die Arbeit": "💼",
  "das Auto": "🚗",
  "der Zug": "🚆",
  "die Straße": "🛣️",
  "die Tür": "🚪",
  "das Fenster": "🪟",
  "der Stuhl": "🪑",
  "das Buch": "📖",
  "die Sprache": "🗣️",
  "die Frage": "❓",
  "die Hand": "✋",
  "das Auge": "👁️",
  "das Geld": "💰",
  "können": "💪",
  "machen": "🛠️",
  "gehen": "🚶",
  "sehen": "👀",
  "sagen": "💬",
  "geben": "🎁",
  "finden": "🔍",
  "essen": "🍽️",
  "trinken": "🥤",
  "sprechen": "🗣️",
  "wohnen": "🏠",
  "kaufen": "🛒",
  "lernen": "📚",
  "arbeiten": "💼",
  "spielen": "🎲",
  "lieben": "❤️",
  "fahren": "🚗",
  "schlafen": "😴",
  "gut": "👍",
  "schlecht": "👎",
  "groß": "🐘",
  "klein": "🐜",
  "neu": "✨",
  "alt": "👴",
  "jung": "👶",
  "schön": "🌹",
  "warm": "🔥",
  "kalt": "🥶",
  "hier": "📍",
  "eins": "1️⃣",
  "zwei": "2️⃣",
  "drei": "3️⃣",
  "die Reise": "🧳",
  "der Urlaub": "🏖️",
  "das Wetter": "🌤️",
  "die Sonne": "☀️",
  "der Regen": "🌧️",
  "der Schnee": "❄️",
  "der Wind": "💨",
  "der Berg": "⛰️",
  "das Meer": "🌊",
  "der Wald": "🌲",
  "das Tier": "🐾",
  "der Hund": "🐕",
  "die Katze": "🐈",
  "der Vogel": "🐦",
  "der Baum": "🌳",
  "die Blume": "🌸",
  "die Farbe": "🎨",
  "das Bild": "🖼️",
  "die Musik": "🎵",
  "der Film": "🎬",
  "das Spiel": "🎲",
  "der Sport": "⚽",
  "die Krankheit": "🤒",
  "der Arzt": "🩺",
  "das Krankenhaus": "🏥",
  "die Apotheke": "💊",
  "das Geschäft": "🏪",
  "der Preis": "🏷️",
  "die Rechnung": "🧾",
  "das Büro": "🏢",
  "die Wohnung": "🏠",
  "der Schlüssel": "🔑",
  "der Aufzug": "🛗",
  "das Frühstück": "🥐",
  "das Abendessen": "🍽️",
  "aufhören": "🛑",
  "bezahlen": "💳",
  "fragen": "❓",
  "helfen": "🤝",
  "hoffen": "🤞",
  "lesen": "📖",
  "schreiben": "✍️",
  "suchen": "🔍",
  "warten": "⏳",
  "zeigen": "👉",
  "einladen": "💌",
  "richtig": "✅",
  "falsch": "❌",
  "schnell": "🐇",
  "langsam": "🐌",
  "früh": "🌅",
  "spät": "🌙",
  "fertig": "✅",
  "besetzt": "🚻",
  "zusammen": "🤝",
  "plötzlich": "⚡",
  "das Ziel": "🎯",
  "die Aufgabe": "📋",
  "der Vorteil": "👍",
  "der Nachteil": "👎",
  "die Beziehung": "💑",
  "die Umwelt": "🌍",
  "die Bildung": "🎓",
  "die Forschung": "🔬",
  "die Wirtschaft": "📈",
  "die Regierung": "🏛️",
  "das Gesetz": "⚖️",
  "der Gedanke": "💭",
  "der Vorschlag": "💡",
  "die Freiheit": "🕊️",
  "die Sicherheit": "🔒",
  "die Gefahr": "⚠️",
  "der Erfolg": "🏆",
  "die Anstrengung": "💪",
  "überlegen": "🤔",
  "verbieten": "🚫",
  "vertrauen": "🤝",
  "vorschlagen": "💡",
  "gefährlich": "⚠️",
  "erfolgreich": "🏆",
  "neugierig": "🔍",
  "zufrieden": "😌",
  "die Strategie": "♟️",
  "die Voraussage": "🔮",
  "die Erleichterung": "😮‍💨",
  "die Zunahme": "📈",
  "die Abnahme": "📉",
  "der Rückgang": "📉",
  "der Anstieg": "📈",
  "das Gleichgewicht": "⚖️",
  "die Vielfalt": "🌈",
  "die Vereinbarung": "🤝",
  "der Vertrag": "📝",
  "hervorheben": "🖍️",
  "nachhaltig": "♻️",
  "zunehmend": "📈",
  "die Errungenschaft": "🏆",
  "der Konsens": "🤝",
  "die Skepsis": "🤨",
  "die Gelassenheit": "😌",
  "abwägen": "⚖️",
  "hinterfragen": "❓",
  "ankurbeln": "🚀",
  "in Frage stellen": "❓",
  "Maßstäbe setzen": "📏",
  "ins Auge fassen": "👁️",
  "Hallo": "👋",
  "Tschüss": "👋",
  "Bitte": "🙏",
  "Danke": "🙏",
  "Ja": "👍",
  "Nein": "👎",
  "der Lehrer": "👨‍🏫",
  "der Schüler": "🧑‍🎓",
  "die Krankenschwester": "👩‍⚕️",
  "der Ingenieur": "👷",
  "der Künstler": "👨‍🎨",
  "die Kunst": "🎨",
  "das Theater": "🎭",
  "das Getränk": "🥤",
  "das Fleisch": "🥩",
  "das Gemüse": "🥦",
  "der Monat": "📅",
  "Hier": "📍",
  "Neu": "🆕",
  "Alt": "👴",
  "Glücklich": "😊",
  "Traurig": "😢",
  "Gut": "👍",
  "Schlecht": "👎",
  "Guten Morgen": "🌅",
  "Guten Tag": "👋",
  "Guten Abend": "🌆",
  "Auf Wiedersehen": "👋",
  "der Bruder": "👦",
  "die Schwester": "👧",
  "die Freundin": "👭",
  "teuer": "💎",
  "heiß": "🔥",
  "Wo": "📍",
  "die Sekunde": "⏱️",
  "die Minute": "⏲️",
  "die Stunde": "🕐",
  "die Woche": "📅",
  "der Morgen": "🌅",
  "der Nachmittag": "🌤️",
  "der Abend": "🌆",
  "die Uhr": "🕰️",
  "der Frühling": "🌸",
  "der Sommer": "☀️",
  "der Herbst": "🍂",
  "der Winter": "❄️",
  "die Uhrzeit": "🕐",
  "die Mitternacht": "🌃",
  "der Mittag": "🕛",
  "die Früh": "🌅",
  "das Datum": "📅",
  "der Kalender": "📆",
  "das Wochenende": "🏖️",
  "der Werktag": "💼",
  "pünktlich": "⏰",
  "dauern": "⏳",
};
